CREATE TABLE IF NOT EXISTS PUBLIC.FILM_GENRE
(
    film_id  INTEGER,
    genre_id INTEGER,
    CONSTRAINT FILM_GENRE_PK PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS PUBLIC.FILM_LIKE
(
    film_id INTEGER,
    user_id INTEGER,
    CONSTRAINT FILM_LIKE_PK PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS PUBLIC.FILMS
(
    film_id      INTEGER NOT NULL AUTO_INCREMENT,
    name         VARCHAR_IGNORECASE,
    description  VARCHAR_IGNORECASE,
    release_date TIMESTAMP,
    duration     INTEGER,
    rating_id    INTEGER,
    CONSTRAINT FILMS_PK PRIMARY KEY (film_id)
);

CREATE TABLE IF NOT EXISTS PUBLIC.FRIENDSHIP
(
    first_user_id  INTEGER,
    second_user_id INTEGER,
    CONSTRAINT FRIENDSHIP_PK PRIMARY KEY (first_user_id, second_user_id)
);

CREATE TABLE IF NOT EXISTS PUBLIC.GENRES
(
    genre_id INTEGER NOT NULL AUTO_INCREMENT,
    name     INTEGER,
    CONSTRAINT GENRES_PK PRIMARY KEY (genre_id)
);

CREATE TABLE IF NOT EXISTS PUBLIC.RATING
(
    rating_id INTEGER NOT NULL AUTO_INCREMENT,
    name      VARCHAR_IGNORECASE,
    CONSTRAINT RATING_PK PRIMARY KEY (rating_id)
);

CREATE TABLE IF NOT EXISTS PUBLIC.USERS
(
    user_id  INTEGER NOT NULL AUTO_INCREMENT,
    email    VARCHAR_IGNORECASE,
    login    VARCHAR_IGNORECASE,
    name     VARCHAR_IGNORECASE,
    birthday TIMESTAMP,
    CONSTRAINT USERS_PK PRIMARY KEY (user_id)
);

ALTER TABLE PUBLIC.FILM_GENRE ADD CONSTRAINT IF NOT EXISTS film_id_fk FOREIGN KEY (film_id) REFERENCES PUBLIC.FILMS(film_id);
ALTER TABLE PUBLIC.FILM_GENRE ADD CONSTRAINT IF NOT EXISTS genre_id_fk FOREIGN KEY (genre_id) REFERENCES PUBLIC.GENRES(genre_id);
ALTER TABLE PUBLIC.FILM_LIKE ADD CONSTRAINT IF NOT EXISTS film_like_id_fk FOREIGN KEY (film_id) REFERENCES PUBLIC.FILMS(film_id);
ALTER TABLE PUBLIC.FILM_LIKE ADD CONSTRAINT IF NOT EXISTS user_like_id_fk FOREIGN KEY (user_id) REFERENCES PUBLIC.USERS(user_id);
ALTER TABLE PUBLIC.FILMS ADD CONSTRAINT IF NOT EXISTS rating_id_fk FOREIGN KEY (rating_id) REFERENCES PUBLIC.RATING(rating_id);
ALTER TABLE PUBLIC.FRIENDSHIP ADD CONSTRAINT IF NOT EXISTS first_user_id_fk FOREIGN KEY (first_user_id) REFERENCES PUBLIC.USERS(user_id);
ALTER TABLE PUBLIC.FRIENDSHIP ADD CONSTRAINT IF NOT EXISTS second_user_id_fk FOREIGN KEY (second_user_id) REFERENCES PUBLIC.USERS(user_id);


